import "./globals.scss";
import type { Metadata } from "next";
import { NavigationComponent } from "./components/navigation/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <NavigationComponent />
        </header>
        <main className="col-12">
          {children}
        </main>
      </body>
    </html>
  );
}
