import "./globals.scss";
import type { Metadata } from "next";
import { NavigationComponent } from "./components/navigation/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container-fluid">
          <div className="row">
            <header className="col-2 no-padding">
              <NavigationComponent />
            </header>
            <main className="col-10 gx-0">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
